version: '3'

services:
  db:
    container_name: local_pipeline_db
    image: postgres:12
    environment:
      - POSTGRES_DB=local_pipeline
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_AUTH_METHOD=trust
    ports:
      - '5432:5432'
  pipeline:
    container_name: local_pipeline
    image: local_pipeline
    command: tail -F anything
    volumes:
      - .:/app
    depends_on:
      - db
